"""
api.py
HTTP wrapper around the pipeline, so a browser front end can use it.

  pip install fastapi uvicorn python-multipart
  uvicorn api:app --reload --port 8000

  http://localhost:8000/docs      interactive contract, generated by FastAPI

The front end is a separate project (see FRONTEND_PROMPT.md). Everything that
needs a GPU, 600MB of weights or a Bolt connection stays here; the browser only
ever sees JSON.

The model loads on the first /analyze call, not at import, so the server starts
instantly and `GET /health` answers while the weights are still loading.
"""

import base64
import io
import uuid
from contextlib import asynccontextmanager

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from PIL import Image, UnidentifiedImageError
from pydantic import BaseModel

from config import ATTRIBUTES, CATEGORY_WARMTH, CLIP_MODEL, MATERIAL_WARMTH, SEASONS
from pipeline import graph, weather

MAX_UPLOAD = 12 * 1024 * 1024  # a phone photo is 3-8MB; past 12 something is wrong


class Tag(BaseModel):
    label: str
    confidence: float


class Analysis(BaseModel):
    id: str | None
    tags: dict[str, Tag]
    warmth: int
    layer: str
    seasons: list[dict]
    summary: str
    cutout: str | None  # data URI of the background-removed image
    saved: bool


@asynccontextmanager
async def lifespan(_app: FastAPI):
    print(f"model {CLIP_MODEL} loads on the first /analyze call")
    print("neo4j reachable" if graph.ping() else "neo4j NOT reachable, --save will fail")
    yield


app = FastAPI(
    title="Garment recognition",
    description="Photo in, garment attributes and the weather it suits out.",
    version="1.0",
    lifespan=lifespan,
)

# A browser front end is served from somewhere else entirely, so it needs CORS.
# Wide open because this listens on localhost and is not exposed; tighten to the
# real origin before putting it anywhere public.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


@app.middleware("http")
async def allow_private_network(request, call_next):
    """
    Chrome's Private Network Access check.

    A page served from a public origin, which is what a hosted front end is,
    must ask permission before it may call a server on the local network. Chrome
    sends a preflight carrying Access-Control-Request-Private-Network and drops
    the request unless the answer carries the matching allow header. CORS alone
    does not cover this, and the failure looks like an ordinary network error in
    the console, which sends people hunting in the wrong place for hours.
    """
    response = await call_next(request)
    if request.headers.get("access-control-request-private-network"):
        response.headers["Access-Control-Allow-Private-Network"] = "true"
    return response


def _summary(tags: dict) -> str:
    def lbl(group):
        return tags.get(group, {}).get("label", "")
    parts = [lbl("color"), lbl("material"), lbl("category")]
    line = " ".join(p for p in parts if p)
    sleeve = lbl("sleeve")
    return f"{line}, {sleeve}" if sleeve else line


def _data_uri(image: Image.Image) -> str:
    buf = io.BytesIO()
    image.save(buf, "PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


@app.get("/health")
def health():
    """Is the database up, and which checkpoint will answer."""
    return {"ok": True, "model": CLIP_MODEL, "neo4j": graph.ping()}


@app.get("/ontology")
def ontology():
    """
    Everything the front end needs to explain an answer: the labels the model
    chooses from, and the warmth table the weather is derived from. Sending it
    means the UI never hardcodes a copy that can drift from config.py.
    """
    return {
        "attributes": ATTRIBUTES,
        "seasons": SEASONS,
        "material_warmth": MATERIAL_WARMTH,
        "category_warmth": {k: {"warmth": w, "layer": l}
                            for k, (w, l) in CATEGORY_WARMTH.items()},
    }


@app.post("/analyze", response_model=Analysis)
async def analyze(
    file: UploadFile = File(..., description="a photo of one garment"),
    save: bool = Form(False, description="store the result in the knowledge graph"),
    cutout: bool = Form(True, description="return the background-removed image"),
):
    raw = await file.read()
    if not raw:
        raise HTTPException(400, "empty upload")
    if len(raw) > MAX_UPLOAD:
        raise HTTPException(413, f"image over {MAX_UPLOAD // 1024 // 1024}MB")

    try:
        image = Image.open(io.BytesIO(raw))
        image.load()
    except (UnidentifiedImageError, OSError):
        raise HTTPException(415, "that file is not an image the server can read")

    # imported here, not at module level: the first import pulls in torch and
    # rembg, and /health should answer before that finishes
    from pipeline import classify, remove_bg

    rgba = remove_bg.cut_out(image)
    rgb = remove_bg.on_white(rgba)

    tags = classify.classify(rgb)
    score = weather.warmth_score(tags)
    layer = weather.layer_of(tags)

    garment_id, saved = None, False
    seasons = weather.seasons_for(score)
    if save:
        garment_id = uuid.uuid4().hex[:12]
        try:
            graph.save_garment(garment_id, file.filename or "upload", tags,
                               warmth=score, layer=layer)
            # asked of the graph, not of the model
            from_graph = graph.infer_weather(garment_id)
            if from_graph:
                seasons = from_graph
            saved = True
        except Exception as e:
            # a dead database must not lose the user their analysis
            raise HTTPException(503, f"analysed fine, but the graph write failed: {e}")

    return Analysis(
        id=garment_id,
        tags={k: Tag(**v) for k, v in tags.items()},
        warmth=score,
        layer=layer,
        seasons=seasons,
        summary=_summary(tags),
        cutout=_data_uri(rgba) if cutout else None,
        saved=saved,
    )


@app.get("/garments")
def garments(category: str | None = None, material: str | None = None,
             style: str | None = None, color: str | None = None,
             sleeve: str | None = None, season: str | None = None):
    """Query what has been stored. One filter at a time, like the CLI."""
    if season:
        return {"filter": {"season": season}, "results": graph.find_by_season(season)}

    for group, value in (("category", category), ("material", material),
                         ("style", style), ("color", color), ("sleeve", sleeve)):
        if value:
            ids = graph.find_by_attribute(group, value)
            return {"filter": {group: value}, "results": [{"id": i} for i in ids]}

    raise HTTPException(400, "pass one filter, e.g. ?material=cotton or ?season=cold")


@app.get("/stats")
def stats():
    """Node and relationship counts, for a dashboard tile."""
    return graph.stats()
