"""
api.py
HTTP wrapper around the pipeline, so a browser front end can use it.

  pip install fastapi uvicorn python-multipart
  uvicorn api:app --reload --port 8000

  http://localhost:8000/docs      interactive contract, generated by FastAPI

The front end is a separate project (see FRONTEND_PROMPT.md). Everything that
needs a GPU, 600MB of weights or a Bolt connection stays here; the browser only
ever sees JSON.

The model loads on the first /analyze call, not at import, so the server starts
instantly and `GET /health` answers while the weights are still loading.
"""

import base64
import io
import uuid
from collections import OrderedDict
from contextlib import asynccontextmanager

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from PIL import Image, UnidentifiedImageError
from pydantic import BaseModel, Field

from config import (
    ATTRIBUTES,
    CATEGORIES_BY_REGION,
    CATEGORY_KIND,
    CATEGORY_REGION,
    CATEGORY_WARMTH,
    CLIP_MODEL,
    CURRENCY,
    CURRENCY_SYMBOL,
    KINDS,
    MATERIAL_WARMTH,
    NON_SEASONAL,
    REGION_GROUPS,
    REGION_TITLES,
    REGIONS,
    SEASON_ESSENTIALS,
    SEASONS,
    SLEEVE_MODIFIER,
    SLEEVED_LAYERS,
    WASH_CARE,
)
from pipeline import closet
from pipeline import feedback as fb
from pipeline import graph, photos, prefs, weather

MAX_UPLOAD = 12 * 1024 * 1024  # a phone photo is 3-8MB; past 12 something is wrong

# The last few analyses, so /feedback can archive the image a correction is
# about without the browser having to upload it a second time. Bounded because
# this is a process-local cache and not storage: restart the server and the
# oldest analyses simply stop being correctable, which is a fair trade for not
# holding decoded images forever.
RECENT_LIMIT = 32
_recent: "OrderedDict[str, dict]" = OrderedDict()


def _remember(analysis_id: str, image: Image.Image, cutout: Image.Image,
              tags: dict, garment_id: str | None, filename: str) -> None:
    _recent[analysis_id] = {"image": image, "cutout": cutout, "tags": tags,
                            "garment_id": garment_id, "filename": filename}
    while len(_recent) > RECENT_LIMIT:
        _recent.popitem(last=False)


class Tag(BaseModel):
    label: str
    confidence: float


class GarmentResult(BaseModel):
    analysis_id: str            # per-garment handle, what /feedback takes
    id: str | None              # graph id, null unless saved
    region: str                 # where on the body this piece belongs
    kind: str | None            # clothing / footwear / headwear / accessory / ...
    tags: dict[str, Tag]
    warmth: int
    layer: str
    seasonal: bool              # false for jewellery, bags, belts: no weather
    seasons: list[dict]
    summary: str
    cutout: str | None          # data URI of this garment's cutout
    saved: bool
    coverage: float             # share of the frame this garment covered
    method: str                 # segment / band / probe -- how it was found
    presence: float | None      # how sure we are anything is there at all
    brand: str | None
    price: float | None
    price_estimate: dict | None  # {tier, known, basis} when a price was guessed


class Analysis(BaseModel):
    """One upload. One photo can hold several pieces, so this is a list."""
    analysis_id: str            # a handle for the whole upload
    count: int
    brand: str | None
    garments: list[GarmentResult]
    # Everything the system saw but would not swear to, in plain sentences: a
    # region it dropped and why, a piece it half-recognised, two instruments
    # disagreeing. A guess printed as a sentence costs the reader nothing; a
    # guess written into the knowledge graph costs them a wrong wardrobe.
    notes: list[str] = Field(default_factory=list)


class MissedItem(BaseModel):
    """Something that was in the photograph and never got mentioned."""
    analysis_id: str | None = Field(
        None, description="the upload or garment this is about, when there is one")
    category: str = Field(description="what was there, from the ontology")
    note: str = ""
    file: bool = Field(
        True, description="also add it to the wardrobe, not just record the miss")


class MissedResult(BaseModel):
    id: str
    category: str
    region: str
    kind: str | None
    garment_id: str | None
    filed: bool
    graph_updated: bool
    total_missed: int


class Feedback(BaseModel):
    """What a person says about one analysis."""
    analysis_id: str
    verdict: str = Field(description="'correct' or 'wrong'")
    corrections: dict[str, str] = Field(
        default_factory=dict,
        description="group -> the label it should have been, e.g. {'category': 'shirt'}",
    )
    note: str = ""


class FeedbackResult(BaseModel):
    id: str
    garment_id: str | None
    verdict: str
    corrections: dict[str, str]
    warmth: int | None
    layer: str | None
    seasons: list[dict]
    graph_updated: bool
    garment_updated: bool
    filed: bool  # true when the correction created the garment it describes
    corpus_size: int


class Details(BaseModel):
    """The two things only the owner of the garment knows."""
    price: float | None = Field(None, description=f"what it cost, in {CURRENCY}")
    clear_price: bool = Field(False, description="remove the stored price")
    wash_temp: int | None = Field(None, description="wash temperature in C")
    wash_cycle: str | None = None
    wash_note: str | None = None


class Preferences(BaseModel):
    preferred_styles: list[str] | None = None
    preferred_colors: list[str] | None = None
    disliked_colors: list[str] | None = None
    home_season: str | None = None
    runs_cold: bool | None = None
    runs_warm: bool | None = None


@asynccontextmanager
async def lifespan(_app: FastAPI):
    print(f"model {CLIP_MODEL} loads on the first /analyze call")
    print("neo4j reachable" if graph.ping() else "neo4j NOT reachable, --save will fail")
    yield


app = FastAPI(
    title="Garment recognition",
    description="Photo in, garment attributes and the weather it suits out.",
    version="1.0",
    lifespan=lifespan,
)

# A browser front end is served from somewhere else entirely, so it needs CORS.
# Wide open because this listens on localhost and is not exposed; tighten to the
# real origin before putting it anywhere public.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST", "PUT", "DELETE"],
    allow_headers=["*"],
)


@app.middleware("http")
async def allow_private_network(request, call_next):
    """
    Chrome's Private Network Access check.

    A page served from a public origin, which is what a hosted front end is,
    must ask permission before it may call a server on the local network. Chrome
    sends a preflight carrying Access-Control-Request-Private-Network and drops
    the request unless the answer carries the matching allow header. CORS alone
    does not cover this, and the failure looks like an ordinary network error in
    the console, which sends people hunting in the wrong place for hours.
    """
    response = await call_next(request)
    if request.headers.get("access-control-request-private-network"):
        response.headers["Access-Control-Allow-Private-Network"] = "true"
    return response


def _summary(tags: dict) -> str:
    def lbl(group):
        return tags.get(group, {}).get("label", "")

    # "solid" is the default state of cloth and adds nothing to a name; every
    # other pattern is the first thing you would say about the garment
    pattern = lbl("pattern")
    parts = [pattern if pattern and pattern != "solid" else "",
             lbl("color"), lbl("material"), lbl("category")]
    line = " ".join(p for p in parts if p)
    sleeve = lbl("sleeve")
    return f"{line}, {sleeve}" if sleeve else line


def _data_uri(image: Image.Image) -> str:
    buf = io.BytesIO()
    image.save(buf, "PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


@app.get("/health")
def health():
    """Is the database up, and which checkpoint will answer."""
    return {"ok": True, "model": CLIP_MODEL, "neo4j": graph.ping()}


@app.get("/ontology")
def ontology():
    """
    Everything the front end needs to explain an answer: the labels the model
    chooses from, and the warmth table the weather is derived from. Sending it
    means the UI never hardcodes a copy that can drift from config.py.
    """
    return {
        "attributes": ATTRIBUTES,
        "seasons": SEASONS,
        "material_warmth": MATERIAL_WARMTH,
        "category_warmth": {
            k: {"warmth": w, "layer": l, "region": CATEGORY_REGION[k],
                "kind": CATEGORY_KIND[k], "seasonal": k not in NON_SEASONAL}
            for k, (w, l) in CATEGORY_WARMTH.items()
        },
        "sleeve_modifier": SLEEVE_MODIFIER,
        "sleeved_layers": sorted(SLEEVED_LAYERS),
        "wash_care": WASH_CARE,
        # the region tables, so the "what did it miss?" form can offer the
        # right categories per region without shipping a second copy of the
        # ontology into the browser
        "regions": REGIONS,
        "region_titles": REGION_TITLES,
        "region_groups": REGION_GROUPS,
        "categories_by_region": CATEGORIES_BY_REGION,
        "kinds": KINDS,
        "season_essentials": SEASON_ESSENTIALS,
        "currency": CURRENCY,
        "currency_symbol": CURRENCY_SYMBOL,
    }


@app.post("/analyze", response_model=Analysis)
async def analyze(
    file: UploadFile = File(..., description="a photo of one or more garments"),
    save: bool = Form(False, description="store the result in the knowledge graph"),
    cutout: bool = Form(True, description="return the background-removed image"),
    brand: str = Form("", description="optional brand tag, used to estimate a price"),
):
    raw = await file.read()
    if not raw:
        raise HTTPException(400, "empty upload")
    if len(raw) > MAX_UPLOAD:
        raise HTTPException(413, f"image over {MAX_UPLOAD // 1024 // 1024}MB")

    try:
        image = Image.open(io.BytesIO(raw))
        image.load()
    except (UnidentifiedImageError, OSError):
        raise HTTPException(415, "that file is not an image the server can read")

    # imported here, not at module level: the first import pulls in torch and
    # rembg, and /health should answer before that finishes
    from pipeline import classify, detect, pricing, remove_bg

    brand = brand.strip() or None
    upload_id = uuid.uuid4().hex[:12]
    filename = file.filename or "upload"

    # Pass one: the clothing. The cloth model segments upper / lower / full
    # body, and each region that carries something is analysed on its own
    # rather than being smeared into a single confused reading.
    seg = remove_bg.segment_garments(image)
    working = seg["image"]
    notes: list[str] = list(seg["notes"])

    results: list[GarmentResult] = []
    found_regions: set[str] = set()

    for piece in seg["pieces"]:
        rgba = piece["cutout"]
        rgb = remove_bg.on_white(rgba)
        # the segmenter already knows where this came from, so the classifier is
        # asked which of the things worn *there* it is, rather than which of
        # fifty-six pieces of clothing. When the whole-image fallback ran, its
        # "full" means "the whole picture" and is not a region at all.
        region = piece["region"] if piece.get("trusted", True) else None
        read = classify.classify_piece(rgb, region=region)
        if read["note"]:
            notes.append(read["note"])
        results.append(_file_piece(
            tags=read["tags"], rgba=rgba, rgb=rgb, brand=brand, save=save,
            filename=filename, cutout=cutout, coverage=piece["coverage"],
            method="segment", presence=None, notes=notes,
        ))
        found_regions.add(results[-1].region)

    # Pass two: everything the cloth model has never seen. Bands measured off
    # the clothing's own bounding box for the head, the feet, the neck and the
    # waist; yes/no probes over the whole photograph for the things with no
    # fixed place in it.
    try:
        extras = detect.find_extras(working, seg["clothing_box"], found_regions)
    except Exception as e:  # noqa: BLE001 - the garments are already read
        print(f"analyze: accessory pass failed ({e})")
        extras = {"items": [], "observations": [
            "The accessory pass could not run on this photo, so anything on the "
            "feet, head, neck or wrists was not looked for. The garments above "
            "are unaffected."
        ]}

    for item in extras["items"]:
        # A band or a probe already established where this is, by geometry. The
        # region cross-check exists to overrule a *mask* that cut a shirt out of
        # the lower body, and applying it here does the opposite of its job: a
        # waistband crop reads as trousers, gets refiled to the lower body, and
        # the photograph comes back with its trousers counted twice. So extras
        # are classified with the region locked.
        if item["region"] in found_regions:
            notes.append(
                f"A {item['category']} was also picked up around the "
                f"{REGION_TITLES.get(item['region'], item['region'])}, but that "
                "region already has a garment cut from the photograph, so it was "
                "treated as the same piece seen twice rather than a second one."
            )
            continue

        crop = item["cutout"]
        if crop is not None:
            rgb = remove_bg.on_white(crop)
            tags = classify.classify(rgb, region=item["region"])
        else:
            # found by a yes/no question about the whole photo, so there is no
            # picture of the thing itself. Reading a colour off the whole
            # photograph would give the outfit's colour, not the belt's, so the
            # rest of the attributes are left for a person to fill in.
            rgb, crop = None, None
            tags = {"category": {"label": item["category"],
                                 "confidence": item["confidence"]}}
        results.append(_file_piece(
            tags=tags, rgba=crop, rgb=rgb, brand=brand, save=save,
            filename=filename, cutout=cutout, coverage=0.0,
            method=item["method"], presence=item["presence"], notes=notes,
        ))
        found_regions.add(results[-1].region)

    notes.extend(extras["observations"])
    if not results:
        notes.append("Nothing in this photograph could be read as a garment.")

    # the whole photograph, remembered under the upload's own handle. A reported
    # miss is about the picture rather than about any one garment in it, so this
    # is the image that should travel with it into the corpus.
    _remember(upload_id, working, None, {}, None, filename)

    return Analysis(analysis_id=upload_id, count=len(results),
                    brand=brand, garments=results, notes=notes)


def _file_piece(*, tags: dict, rgba, rgb, brand, save: bool, filename: str,
                cutout: bool, coverage: float, method: str,
                presence: float | None, notes: list[str]) -> GarmentResult:
    """
    One piece, from tags to a stored garment.

    Shared by both passes because the answer to "what is this and what weather
    is it for" must not depend on which instrument found it: a boot detected in
    a band and a boot uploaded on its own have to come out identical, or the
    wardrobe holds two kinds of truth.
    """
    from pipeline import pricing

    category = tags.get("category", {}).get("label")
    region = CATEGORY_REGION.get(category or "", "unplaced")
    score = weather.warmth_score(tags)
    layer = weather.layer_of(tags)
    seasons = weather.seasons_for(score, tags)
    est_price, est_info = pricing.estimate(brand, category)

    garment_id, saved = None, False
    if save:
        garment_id = uuid.uuid4().hex[:12]
        try:
            photo = photos.save(garment_id, rgba) if rgba is not None else None
            graph.save_garment(
                garment_id, filename, tags,
                warmth=score, layer=layer, photo=photo, brand=brand,
                price=est_price, price_source="estimated" if est_price else None,
                region=region, detection=method,
            )
            from_graph = graph.infer_weather(garment_id)
            if from_graph:
                seasons = from_graph
            saved = True
        except Exception as e:
            photos.delete(garment_id)
            raise HTTPException(503, f"analysed fine, but the graph write failed: {e}")

    analysis_id = uuid.uuid4().hex[:12]
    _remember(analysis_id, rgb, rgba, tags, garment_id, filename)

    return GarmentResult(
        analysis_id=analysis_id,
        id=garment_id,
        region=region,
        kind=CATEGORY_KIND.get(category or ""),
        tags={k: Tag(**v) for k, v in tags.items()},
        warmth=score,
        layer=layer,
        seasonal=weather.seasonal(tags),
        seasons=seasons,
        summary=_summary(tags),
        cutout=_data_uri(rgba) if cutout and rgba is not None else None,
        saved=saved,
        coverage=coverage,
        method=method,
        presence=presence,
        brand=brand,
        price=est_price,
        price_estimate=est_info if est_price is not None else None,
    )


@app.post("/feedback", response_model=FeedbackResult)
def submit_feedback(body: Feedback):
    """
    Tell the system it got one wrong, and what the answer should have been.

    Three things happen, and they are worth keeping distinct:

      1. the correction is appended to data/feedback/corrections.jsonl with the
         image, which is training data for a later run of finetune.py
      2. a Correction node goes into the graph, so the confusion table can be
         queried in Cypher
      3. if the garment was saved, its edges are re-pointed at the corrected
         labels and the weather is re-derived from them on the spot

    Only the third is instant. The model itself does not change until somebody
    retrains it on the corpus, and pretending otherwise would be a lie told by
    a progress bar.
    """
    if body.verdict not in fb.VERDICTS:
        raise HTTPException(400, f"verdict must be one of {list(fb.VERDICTS)}")

    remembered = _recent.get(body.analysis_id)
    if remembered is None:
        raise HTTPException(
            404,
            "that analysis is no longer in memory. Analyse the photo again and "
            "flag the new result.",
        )

    # a correction that invents a label would poison both the graph and the
    # training corpus, so the vocabulary is the one in config.py or nothing
    for group, label in body.corrections.items():
        if group not in ATTRIBUTES:
            raise HTTPException(400, f"unknown attribute group '{group}'")
        if label not in ATTRIBUTES[group]:
            raise HTTPException(
                400, f"'{label}' is not a {group} this system knows. "
                     f"Pick one of: {', '.join(ATTRIBUTES[group])}"
            )
    if body.verdict == "wrong" and not body.corrections and not body.note.strip():
        raise HTTPException(400, "say what was wrong: pick a label or write a note")

    tags = remembered["tags"]
    garment_id = remembered["garment_id"]
    feedback_id = uuid.uuid4().hex[:12]

    fb.record(
        feedback_id, body.verdict, tags, body.corrections,
        note=body.note, garment_id=garment_id, model=CLIP_MODEL,
        image=remembered["image"],
    )

    # the corrected picture of the garment: predicted labels with the person's
    # answers written over them, which is what the warmth has to be recomputed on
    fixed = {g: dict(t) for g, t in tags.items()}
    for group, label in body.corrections.items():
        fixed.setdefault(group, {})["label"] = label
        fixed[group]["confidence"] = 1.0

    warmth = weather.warmth_score(fixed)
    layer = weather.layer_of(fixed)
    seasons = weather.seasons_for(warmth, fixed)

    graph_updated = garment_updated = filed = False
    try:
        if garment_id and body.corrections:
            graph.apply_correction(garment_id, body.corrections, warmth, layer)
            garment_updated = True
        elif body.corrections:
            # Nothing was stored, and a person has just said what this garment
            # actually is. That answer is better than anything the model
            # produced, so the garment is filed now, under the corrected label,
            # marked as a human answer. Saying "wrong, it is a hoodie" puts it
            # on the hoodie hook, which is the only place it belongs.
            garment_id = uuid.uuid4().hex[:12]
            # a piece found by a whole-photo probe has no picture of itself, so
            # it is filed without one rather than not filed at all
            cut = remembered.get("cutout")
            photo = photos.save(garment_id, cut) if cut is not None else None
            graph.save_garment(garment_id, remembered["filename"], fixed,
                               warmth=warmth, layer=layer, photo=photo,
                               source="human",
                               region=CATEGORY_REGION.get(
                                   fixed.get("category", {}).get("label", "")))
            graph.apply_correction(garment_id, body.corrections, warmth, layer)
            filed = garment_updated = True

        graph.save_correction(feedback_id, body.verdict, tags, body.corrections,
                              note=body.note, garment_id=garment_id, model=CLIP_MODEL)
        graph_updated = True

        if garment_id:
            from_graph = graph.infer_weather(garment_id)
            if from_graph:
                seasons = from_graph
    except Exception as e:
        # the corpus write already succeeded; a dead database must not throw
        # away what the person just told us
        print(f"feedback {feedback_id} saved to disk but not to Neo4j: {e}")

    return FeedbackResult(
        id=feedback_id,
        garment_id=garment_id,
        verdict=body.verdict,
        corrections=body.corrections,
        warmth=warmth,
        layer=layer,
        seasons=seasons,
        graph_updated=graph_updated,
        garment_updated=garment_updated,
        filed=filed,
        corpus_size=len(fb.load()),
    )


@app.post("/missing", response_model=MissedResult)
def report_missing(body: MissedItem):
    """
    Say what was in the photograph that the system never mentioned.

    This is the other half of being wrong. /feedback handles "you called this a
    shirt and it is a blouse"; there is no way to express "there were boots in
    that photo" as a correction, because there is nothing to correct. Until this
    endpoint existed the only failure the system could hear about was the one it
    had already half-committed to.

    Two things happen, and the second is optional:

      1. the miss is recorded -- on disk, and as a Missing node pointing at the
         Category it should have seen, which makes "what is this system blind
         to" a Cypher query rather than an impression
      2. unless `file` is false, the piece is added to the wardrobe there and
         then, marked source='human', because a person naming a garment they
         own is better evidence than anything the model produces

    What it cannot do is give the piece a picture. Nobody drew a box around the
    boots, so the garment is filed without one and the wardrobe card says so.
    """
    category = body.category.strip()
    if category not in ATTRIBUTES["category"]:
        raise HTTPException(
            400,
            f"'{category}' is not something this system knows. It knows "
            f"{len(ATTRIBUTES['category'])} pieces across {len(REGIONS)} regions; "
            "pick one of those, or say it in the note and it becomes a case for "
            "widening the ontology.",
        )

    region = CATEGORY_REGION[category]
    missing_id = uuid.uuid4().hex[:12]
    remembered = _recent.get(body.analysis_id or "")

    tags = {"category": {"label": category, "confidence": 1.0}}
    warmth = weather.warmth_score(tags)
    layer = weather.layer_of(tags)

    garment_id = None
    if body.file:
        garment_id = uuid.uuid4().hex[:12]

    fb.record_missing(
        missing_id, category, region=region, note=body.note,
        analysis_id=body.analysis_id, garment_id=garment_id, model=CLIP_MODEL,
        image=remembered["image"] if remembered else None,
    )

    graph_updated = filed = False
    try:
        if garment_id:
            graph.save_garment(
                garment_id, remembered["filename"] if remembered else "reported",
                tags, warmth=warmth, layer=layer, photo=None, source="human",
                region=region, detection="reported",
            )
            filed = True
        graph.save_missing(missing_id, category, region=region, note=body.note,
                           analysis_id=body.analysis_id,
                           garment_id=garment_id if filed else None)
        graph_updated = True
    except Exception as e:
        # the disk record already succeeded; a dead database must not throw away
        # what the person just told us
        print(f"missing {missing_id} saved to disk but not to Neo4j: {e}")
        garment_id = garment_id if filed else None

    return MissedResult(
        id=missing_id,
        category=category,
        region=region,
        kind=CATEGORY_KIND.get(category),
        garment_id=garment_id,
        filed=filed,
        graph_updated=graph_updated,
        total_missed=len(fb.load_missing()),
    )


@app.get("/missing/stats")
def missing_stats():
    """
    What this system is blind to, from both stores.

    The region breakdown is the one that matters. Misses scattered across every
    region are hard photographs; forty misses all on the feet are a system that
    is not looking at feet, which is a fixable thing rather than a fact of life.
    """
    out = {"corpus": fb.missing_summary(), "graph": None}
    try:
        out["graph"] = graph.missing_stats()
    except Exception as e:
        out["graph_error"] = str(e)
    return out


@app.get("/feedback/stats")
def feedback_stats():
    """
    What the correction loop has collected so far, from both stores.

    `corpus` is the file on disk and is always available; `graph` is the same
    thing counted in Cypher and is absent when Neo4j is down. They should
    agree, and when they do not, the file is the one to trust: it is written
    first and unconditionally.
    """
    out = {"corpus": fb.summary(), "graph": None}
    try:
        out["graph"] = graph.correction_stats()
    except Exception as e:
        out["graph_error"] = str(e)
    return out


@app.get("/garments")
def garments(category: str | None = None, material: str | None = None,
             style: str | None = None, color: str | None = None,
             sleeve: str | None = None, season: str | None = None):
    """Query what has been stored. One filter at a time, like the CLI."""
    if season:
        return {"filter": {"season": season}, "results": graph.find_by_season(season)}

    for group, value in (("category", category), ("material", material),
                         ("style", style), ("color", color), ("sleeve", sleeve)):
        if value:
            ids = graph.find_by_attribute(group, value)
            return {"filter": {group: value}, "results": [{"id": i} for i in ids]}

    raise HTTPException(400, "pass one filter, e.g. ?material=cotton or ?season=cold")


@app.get("/wardrobe")
def wardrobe(region: str | None = None):
    """
    Everything stored, with its picture, grouped the way a wardrobe is.

    `region` filters to one part of the body and is answered by traversing
    (Garment)->(Category)-[:WORN_ON]->(Region), so clicking the mannequin is a
    graph question and not a filter applied in the browser.
    """
    if region and region not in (*REGIONS, "unplaced"):
        raise HTTPException(
            400, f"region must be one of {', '.join(REGIONS)} or unplaced")
    items = graph.wardrobe(region)
    for item in items:
        item["photo_url"] = f"/garments/{item['id']}/image" if item.get("photo") else None
        item["wash"] = closet.wash_for(item)
    return {
        "region": region,
        "regions": graph.region_counts(),
        "count": len(items),
        "items": items,
    }


def _enriched_wardrobe() -> list[dict]:
    """The whole wardrobe with the derived fields the closet logic needs."""
    items = graph.wardrobe(None)
    for item in items:
        item["photo_url"] = f"/garments/{item['id']}/image" if item.get("photo") else None
        item["wash"] = closet.wash_for(item)
    return items


@app.get("/wardrobe/profile")
def wardrobe_profile():
    """
    What this wardrobe is, as a whole: the styles and colours it leans on, how
    it splits across the body, what it is worth, which seasons it can dress for
    and which it cannot. This is about one person's own clothes, not about the
    model; accuracy is not on this page and does not belong on it.
    """
    return {"currency": CURRENCY, "currency_symbol": CURRENCY_SYMBOL,
            **closet.profile(_enriched_wardrobe())}


@app.get("/recommend")
def recommend(season: str | None = None):
    """
    Assemble one outfit for the weather from what the person owns, tilted toward
    their stated taste. A greedy per-slot heuristic, not a learned model; it is
    honest about what it cannot cover rather than padding the outfit out.
    """
    if season and season not in {s["name"] for s in SEASONS}:
        raise HTTPException(400, f"unknown season '{season}'")
    return {"currency": CURRENCY, "currency_symbol": CURRENCY_SYMBOL,
            "preferences": prefs.load(),
            **closet.recommend(_enriched_wardrobe(), prefs.load(), season)}


@app.get("/preferences")
def get_preferences():
    """The single person's stated taste. Used to break ties, never to hide clothes."""
    return prefs.load()


@app.put("/preferences")
def put_preferences(body: Preferences):
    """Update taste. Colours and styles are validated against the ontology."""
    update = {k: v for k, v in body.model_dump().items() if v is not None}
    for field in ("preferred_colors", "disliked_colors"):
        for c in update.get(field, []):
            if c not in ATTRIBUTES["color"]:
                raise HTTPException(400, f"'{c}' is not a colour this system knows")
    for st in update.get("preferred_styles", []):
        if st not in ATTRIBUTES["style"]:
            raise HTTPException(400, f"'{st}' is not a style this system knows")
    if update.get("home_season") and update["home_season"] not in {s["name"] for s in SEASONS}:
        raise HTTPException(400, "unknown home_season")
    return prefs.save(update)


@app.put("/garments/{garment_id}/details")
def set_details(garment_id: str, body: Details):
    """
    Set what the owner knows and the model cannot see: the price, and how the
    garment is actually washed. Returns the garment's refreshed wash card, which
    now reflects the override.
    """
    if body.price is not None and body.price < 0:
        raise HTTPException(400, "a price cannot be negative")
    if body.wash_temp is not None and not (0 <= body.wash_temp <= 95):
        raise HTTPException(400, "wash temperature should be between 0 and 95 C")

    found = graph.set_details(
        garment_id, price=body.price, clear_price=body.clear_price,
        wash_temp=body.wash_temp, wash_cycle=body.wash_cycle, wash_note=body.wash_note,
    )
    if not found:
        raise HTTPException(404, "no garment with that id")

    item = next((i for i in graph.wardrobe(None) if i["id"] == garment_id), None)
    return {"id": garment_id, "price": item.get("price") if item else None,
            "wash": closet.wash_for(item) if item else None}


@app.get("/garments/{garment_id}/image")
def garment_image(garment_id: str):
    """The stored cutout. Cached hard: a garment's picture never changes."""
    path = photos.path(garment_id)
    if path is None:
        raise HTTPException(404, "no picture stored for that garment")
    return FileResponse(path, media_type="image/png",
                        headers={"Cache-Control": "public, max-age=31536000, immutable"})


@app.delete("/garments/{garment_id}")
def delete_garment(garment_id: str):
    """
    Take one garment out of the wardrobe.

    The node goes, its picture goes, and any Correction about it stays: what the
    model got wrong is evidence about the model, and throwing away the garment
    does not unmake the mistake.
    """
    gone = graph.delete_garment(garment_id)
    if not gone:
        raise HTTPException(404, "no garment with that id")
    photos.delete(garment_id)
    return {"deleted": garment_id, "photo_removed": photos.path(garment_id) is None}


@app.get("/insights")
def insights():
    """
    Everything countable about what is stored: per category, material, colour,
    style and layer, the warmth histogram, the season coverage, and how much of
    it a person corrected.

    None of it is accuracy. This describes the contents of one wardrobe;
    accuracy is measured in evaluate.py against labelled ground truth, and the
    two must not be presented as the same kind of number.
    """
    out = {"graph": graph.insights(), "photos": photos.usage(),
           "feedback": fb.summary(), "missed": fb.missing_summary(),
           "model": CLIP_MODEL}
    try:
        out["corrections"] = graph.correction_stats()
    except Exception as e:
        out["corrections_error"] = str(e)
    try:
        out["misses"] = graph.missing_stats()
    except Exception as e:
        out["misses_error"] = str(e)
    return out


@app.get("/stats")
def stats():
    """Node and relationship counts, for a dashboard tile."""
    return graph.stats()
